### ISSUE TITLE
Feature Request - Help button hide on Terrain Summit

### ISSUE THREAD

**Issue by AceLeader2023** [pete-mc/Summit#20]
Can the help button be hidden on the Terrain Summit extension??

<img width="238" alt="image" src="https://github.com/pete-mc/Summit/assets/110509017/096d8c6b-1eec-4c48-a69b-74d1c2016d08">

**Comment by pete-mc** [comment]
Thanks for letting me know. Which report is that happening on? I can't see it on my side. What browser are you using Chrome or Edge?

**Comment by AceLeader2023** [comment]
All good. On all reports, unfortunately. And I am using Chrome.

**Comment by pete-mc** [comment]
![weird issue](https://github.com/pete-mc/Summit/assets/8443346/4a3c840c-31ce-43c0-a425-524541543972)
 Do you think it could be this? or is this separate? it might be my table and interacting weirdly.

**Comment by AceLeader2023** [comment]
Correct, it is that help button.

Sorry for not being detailed enough

**Comment by pete-mc** [comment]
All good, I have added a new tool to be able to control some display settings in Terrain. The first item on the page is hiding the help button but I will add some more items as I have time like making some of the tables and forms display nicer and use less room. I will close this ticket assuming that this will sort out your issue. Please reopen if it does not help. It will be released in 2.4.0 in a few days.
