### ISSUE TITLE
Fix Required - Drop Down Menu

### ISSUE THREAD

**Issue by ScoutLeaderDid** [pete-mc/Summit#32]
Hi Peter,

In your latest release you made some good improvements. I am suggesting a fix for the following

Request #1 -  How the drop menu for Reports works. Every time I click on a sub-menu say Milestone Planning Report, the Reports main menu condenses. The same happens when I select any of the sub-menus. This is quite irritating. I would to see the parent menu option display all the submenus when I select one of them. So this will allow the user to view the submenu options regardless where they are in the parent menu display. I hope this makes sense.

![Summit01 drop Down Menu](https://github.com/pete-mc/Summit/assets/155197725/5f547ca8-6aa2-437e-9678-dbf714eb32a6)

I am happy to discuss further.

Regards,
Didier

**Comment by pete-mc** [comment]
Thanks for raising this, it was on the back on my mind and I kept forgetting about sorting it out. It will be in the next release for sure.

**Comment by pete-mc** [comment]
Fixed and will be released in version 2.4.0.
