### ISSUE TITLE
Support Leader Access

### ISSUE THREAD

**Issue by wilsteady** [pete-mc/Summit#34]
Could we get allowance for Support Leaders to use the add-on? It just displays an error message when trying to open within Terrain. I've tried doing a full clear of the cache and cookies with Terrain first to no avail.

**Comment by pete-mc** [comment]
Hmm I am not sure how the support leaders work, I have tested with youth member accounts. I might need to do a screenshare with someone who has one of these accounts. I did not know there was even a support leader option. Do you know how you get them setup? I might be able to get one for my wife and can test with that.

**Comment by wilsteady** [comment]
The Support Leader roles within Terrain are for District Leaders and above. We can request access to another formation for a set duration as either Read/Write or Write only. If we get Write access, we can do everything a Group Leader can within that Formations terrain. 

This is different to just being added to a formation as an adult leader, as when you get added you can view members and modify roles and UC, but you can't change Patrols unless you're from that group; Support Leader role lets you modify patrols. 

It also has a 'Branch Life' section seperate from Group Life where you can view all the groups you have access to in one place. 

Happy to do a show and tell some time. Topo is having to make a few changes too as we had it working, but a Terrain Update over Xmas has broken whatever was working.

**Comment by pete-mc** [comment]
Now I know what you are talking about my DCL has been having the same issue with Topo. 

Can you do me a favor and go to Developer Tools in chrome and run some code to give me a list of the roles you have?
Screenshot is below, steps are 1: click chrome menu, 2: click more tools, 3: click Developer Tools, 4: click Console Tab, 5: Paste the code in the cursor (as shown in the yellow box) and press Enter. Then copy the infomation in the Blue box and send it back to me.
![image](https://github.com/pete-mc/Summit/assets/8443346/76e89c79-2d3a-4fd9-b73e-ebaa7c787171)

**Comment by wilsteady** [comment]
Find attached listing. Just a tad long. 
![image](https://github.com/pete-mc/Summit/assets/12633684/2dc8fe17-61c3-4a81-b84f-7dc543c15d60)

**Comment by pete-mc** [comment]
Thanks for that, it looks like it has to do with the new roles. Now I can see the names of the permissions, like support-leader-group-readwrite I should be able to add them to my code so it knows what to do. I will try to sort this for the next release.

**Comment by pete-mc** [comment]
I am fairly sure I have solved this issue but I can't test it as I dont have the role. The fix will be in the next release, I will keep this one open until I can verify that it is working after the release.

Also, apologies for not giving you the code in text, I just re-read this issue and the images and noticed I only gave you the code in a screenshot. Sorry!

**Comment by wilsteady** [comment]
Hey Pete, just tried it and it's all working perfectly.

**Comment by pete-mc** [comment]
Awesome, thanks for the update. Let me know if there is any other summary views or features that would be handy at the district, region and branch levels.
