### ISSUE TITLE
Present Awards - Presenting badge report

### ISSUE THREAD

**Issue by rogirik** [pete-mc/Summit#36]
Couple of things
add stage on OAS so that you can see which stage you have presented
Section on milestones in case this hasn't been done in previous sections

**Comment by pete-mc** [comment]
Good ideas I will add them to the next update.

**Comment by hartnickaus** [comment]
Intro to Section - could this have section as well. Again in case not done marked presented in previous section

**Comment by AceLeader2023** [comment]
Special Interest Areas - could they have what area

**Comment by pete-mc** [comment]
Similar request by [James Warnock](https://www.facebook.com/groups/1371834673696135/user/1263991489/?__cft__[0]=AZVU4ZWCwYAR4X12BeD5Rq9KQAQHDjHruIwHk0UiHw2xKBV8JEQGw4Ezl7kX3G8TaZE7qKZk2zfDtxieNF7meS5XmRumj2QvMyHvBSN6OOr-Sk_bcITsCQFFm8cBm8lLCjeBgxjDn_RCHxxOMUIjc0r6II6hAg10H1vs5ND6-86NZnpInmf2DryR07rRxCBcWLU&__tn__=-UC%2CP-R): https://www.facebook.com/groups/terrainsummit/permalink/1373994083480194/

**Comment by pete-mc** [comment]
Completed, will be in 2.4.0 when released.
