### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by Frostbite1983** [pete-mc/Summit#38]
Not too sure if I have done anything wrong or missed a step, however after logging into Terrain with the Browser addon installed I get the error"404" when I click on the Summit tab.
![Screenshot 2023-12-30 214000](https://github.com/pete-mc/Summit/assets/155233888/197a3109-8a81-4e30-9267-45207e17b7dc)

**Comment by pete-mc** [comment]
Is this on chrome or edge? it looks like it is running version 2.1 or older (newer versions have the version number near the logo). If it is the bug I am thinking of, then it was updated in v2.2.

If you are using Chrome, the latest version is 2.3. Edge is still as I think the Microsoft checking team are on holidays. Edge can actually install the version from the Chrome store too (just make sure you remove the Edge one first).

Can you update the extension as check if that has sorted out the issue?

**Comment by Frostbite1983** [comment]
Correct, it was 2.1. i have now added it on chrome and works. thanks :)

**Comment by pete-mc** [comment]
Awesome, hopefully Microsoft will push the later versions out soon. But either store works the same for both browsers.
