### ISSUE TITLE
Bug: Bulk Calendar Edit

### ISSUE THREAD

**Issue by hartnickaus** [pete-mc/Summit#39]
Using Chrome Extension v2.3.0

When adding additional events, appears to just keep adding the 7 days to the original entry.

1st was for Feb 1st, second was for Feb 8th, third was for Feb 8th rather than Feb 15th
![image](https://github.com/pete-mc/Summit/assets/30915527/600cd081-0883-4503-a868-ea5295bb012a)

**Comment by pete-mc** [comment]
Thanks I will fix that in the next release.

**Comment by pete-mc** [comment]
Completed and ready for next release.
