### ISSUE TITLE
Bug: Incorrect names listed on Milestone Planning Report

### ISSUE THREAD

**Issue by CrispyCamper** [pete-mc/Summit#42]
**Describe the bug**
Although the currently selected unit is Cubs (as seen in top right), and Summit says it is showing information on Cubs, the names listed are those of the scout unit.
(You can tell that the names listed are not the Cubs by seeing Issue #43 where there are only 6 members in the cub unit.)

**Expected behavior**
The listed names should be those in the unit you currently have selected in the top right corner.

**Screenshots**
![20240101_163550](https://github.com/pete-mc/Summit/assets/110330806/09eab7f1-277c-40dc-9f7d-e130932a0e54)

 - Device: Samsung Galaxy Tab S9 FE+
 - OS: Android
 - App Type: Mobile app
 - Version V2.3.0

**Additional notes**
Probably unrelated, but the buttons at the top (Print & Export to CSV) are also tripled up.

**Comment by pete-mc** [comment]
Thanks I will add this to the next release.

**Comment by pete-mc** [comment]
Fixed in 2.4.0, awaiting release.
