### ISSUE TITLE
Bug: Incorrect information on Milestone Planning Report

### ISSUE THREAD

**Issue by CrispyCamper** [pete-mc/Summit#43]
**Describe the bug**
The Milestone Planning Report shows partially incorrect information. In this example, 'B' is all correct, but 'A', 'C', 'H', 'M', & 'P' all have incorrect leads listed. Compare this report to the equivalent Topo report which shows the correct information. 

**To Reproduce**
1. Generate a Topo Milestone report
2. Generate a Summit Milestone Planning report
3. Check for inaccuracies 

**Expected behavior**
The correct information should be shown, matching the Topo report

**Screenshots**
![20240101_172841](https://github.com/pete-mc/Summit/assets/110330806/1728e60f-0dd7-49f3-9cfc-d230e636bacd)
'C' has 1 lead left, 'A', 'H', 'M', & 'P' all have 2 leads left. (Correct)

![Screenshot_20240101_173104_Terrain  Summit](https://github.com/pete-mc/Summit/assets/110330806/3c71b9a6-0062-49e5-b16c-cc145729ba76)
'C' supposedly has 2 leads left, 'A', 'H', 'M', & 'P' all supposedly have 3 leads left.

 - Device: Samsung Galaxy Tab S9 FE+
 - OS: Android
 - App Type: Mobile app
 - Version: V2.3.0

**Additional notes**
Again, as mentioned in Issue #42 the buttons at the top (Print & Export to CSV) are this time doubled up.

**Comment by AceLeader2023** [comment]
This is experienced on the Chrome version of 2.3.0 as well. 

I am also experiencing incorrect numbers in the challenge areas as well. - I would be happy to provide sample if needed.

**Comment by pete-mc** [comment]
Adding to next release backlog. Thanks for taking the effort to explain this really well, it speeds up the time it takes to sort out the issues.

**Comment by pete-mc** [comment]
Worked out the issue, my totals were the wrong way around between leads and assists. This will released be in 2.40.
