### ISSUE TITLE
Present Awards -  intro to section award

### ISSUE THREAD

**Issue by iramoojk** [pete-mc/Summit#45]
**Describe the bug**
When viewing awards in “present awards” intro to section is displayed but doesn’t show which section is awarded, ie joeys, cubs. Would be useful to display the section it is awarded in.

**Comment by pete-mc** [comment]
Thanks there are a few other name changes that have been requested I will do them all in the next update. Thanks for letting me know.

**Comment by pete-mc** [comment]
Completed - Will be released in 2.4.0
