### ISSUE TITLE
Bug: Summit Extension does not work when Terrain is installed as app (PC)

### ISSUE THREAD

**Issue by CrispyCamper** [pete-mc/Summit#46]
**Describe the bug**
When Terrain is installed as a web app on a computer, the Summit extension does not work. If Terrain is visited in a web browser, it appears as expected, but not when opening Terrain as a web app.

**To Reproduce**
1. Go to '[terrain.scouts.com.au](terrain.scouts.com.au)' in a web browser (in this example, I use Chrome)
2. In the far right of the address bar, click the computer with down arrow icon and install the app
3. Terrain will open as a web app (If you have the Summit extension, it will appear in the app like you'd expect, until you close it)
4. Open the Terrain app on your PC 
5. See there is no Summit button despite having the extension

**Expected behavior**
The green Summit button should appear as it does in a web browser

**Screenshots**
![Screenshot (121)](https://github.com/pete-mc/Summit/assets/110330806/3f887e36-9ffe-4c5f-81ed-8fd6db502f31)
Terrain in a web browser (Chrome)

![Screenshot (120)](https://github.com/pete-mc/Summit/assets/110330806/4c6d1c2f-5ac8-4752-afdd-16d893c40057)
Terrain open in the web app. Summit extension is installed (but greyed out), however no button exists

 - Device: HP Laptop 15s-fq4011TU 
 - OS: Windows 11 22H2
 - Chrome Version: 120.0.6099.130
 - App Type: Chrome Extension
 - Version: V2.3.0

**Comment by ScoutLeaderBear** [comment]
if you refresh the app by pressing f5 the tab will appear

**Comment by CrispyCamper** [comment]
> if you refresh the app by pressing f5 the tab will appear

Until you close and reopen the app

**Comment by AceLeader2023** [comment]
I could reproduce the issue. 

After pressing the f5 button the extension appeared.

**Comment by pete-mc** [comment]
Yeah there is something funky about the url when it opens as an app and the extension does not recognise it as the terrain website. Refreshing will clear out the weird link which is why it works until you close and reopen. It might take me some time to work on this one as I have quite a few issues building up. I will add this to the release after next (2.5.0).

**Comment by pete-mc** [comment]
Worked out the issue, the fix will be in the next version 2.5.1 which should be released by google in a few days.
