### ISSUE TITLE
Bug: How to Update to the Latest Version 2.4

### ISSUE THREAD

**Issue by ScoutLeaderDid** [pete-mc/Summit#49]
Hi Peter,
I noticed version 2.4 has been released. How do I update my current version of 2.3 to 2.4? It does seem to be automatic.
Regards,
Didier

**Comment by ScoutLeaderDid** [comment]
It appears to have resolved itself, thanks

**Comment by pete-mc** [comment]
No worries :)

**Comment by CrispyCamper** [comment]
I'm having the same issue. On both PC and mobile app. Do I need to uninstall and reinstall the browser extension? There doesn't seem to be an option on update it. And what about the mobile app?

**Comment by pete-mc** [comment]
It should push automatically but they can take a couple of days at times. To speed it up you can remove it and add it back and it will be the latest version.

**Comment by pete-mc** [comment]
@CrispyCamper sorry forget to mention the mobile app has been sent to google and should be approved and released soon.
