### ISSUE TITLE
Bug: summit not loading right (android app)

### ISSUE THREAD

**Issue by ScoutLeaderBear** [pete-mc/Summit#52]
https://github.com/pete-mc/Summit/assets/155511298/3e27747d-353b-4079-abe9-8c2a8e850071

Started doing this as soon as I updated app and loading it up.

**Comment by pete-mc** [comment]
@ScoutLeaderBear Thanks for letting me know I will revert the store version for now and push a new update ASAP.

**Comment by CrispyCamper** [comment]
Mine did that for a bit too, but I left it and it soon opened up normally.

**Comment by AceLeader2023** [comment]
Mine did it too. But loaded in the end.

**Comment by pete-mc** [comment]
Brought forward my change from Cordova to Flutter for mobile app building so there are more options. Have fixed this issue at the same time.
