### ISSUE TITLE
Bug: Bulk Calendar

### ISSUE THREAD

**Issue by AceLeader2023** [pete-mc/Summit#60]
**Describe the bug**
I am trying to create a calendar input **without** a lead or an assist

**To Reproduce**
1. Go to bulk calendar
2. Fill in details apart from lead and assist

**Expected behavior**
Expected behaviour is that it inputs the data without a lead or assist

**Screenshots**
Getting this error after pressing the submit button
![image](https://github.com/pete-mc/Summit/assets/110509017/2b9b9655-0522-4597-9f75-9b203d45a9e4)

- Device : PC
 - OS: Windows
 - App Type Chrome
 - Version 2.4.0

**Additional context**
Most of the time Cub Leaders don't know what youth will be leading or assisting on a night before the night happens. Therefore most of the time.

**Comment by pete-mc** [comment]
Good pick up, for some reason I though they were mandatory fields.

Should be an easy fix.

**Comment by pete-mc** [comment]
Fixed in 2.5.0, release should be out shortly.
