### ISSUE TITLE
Bug: Terrain Summit (android) won't install

### ISSUE THREAD

**Issue by ScoutLeaderBear** [pete-mc/Summit#61]
Tried installing the new update for the app.
Google says it won't in install
![inbound5104193036892389276](https://github.com/pete-mc/Summit/assets/155511298/b5c2163b-3062-42c2-8837-17461ad1e680)

**Comment by pete-mc** [comment]
To help fix some of the problems I have changed the development platform that it was built on. It may require you to uninstall the old one first, can you give that a go?

**Comment by ScoutLeaderBear** [comment]
Yep that worked. Thanks
