### ISSUE TITLE
Milestone viewing in terrain 

### ISSUE THREAD

**Issue by iramoojk** [pete-mc/Summit#63]
Attempting to view scouts milestones under there login, used 2x different computers using windows with the summit extension installed. Was unable to get to the milestone page, kept going back to the youth Basecamp.

Turned off the extension and works every time. 

Is there a possible bug with summit extension or am I doing something wrong?

**Comment by pete-mc** [comment]
Just to confirm are you logged in as them with a username and password or are you using your login and going to manage pathways?

**Comment by iramoojk** [comment]
I’m using my login and then going to manage pathways. Previously it worked without SUMMIT added on but assuming it may to be with SUMMIT if it works when turn summit off

**Comment by pete-mc** [comment]
Thanks I have been able to replicate the issue, I will try to get a fix out asap.
