### ISSUE TITLE
Bug: Incorrect Title - Record Badge Presentation 

### ISSUE THREAD

**Issue by AceLeader2023** [pete-mc/Summit#70]
**Describe the bug**
Repeat of Unit Name in title

**To Reproduce**
Go to Record Badge Presentation 

**Expected behavior**
Should say Record Badge Presentation - [Unit Name]

**Screenshots**
![Screenshot_20240117_220237.jpg](https://github.com/pete-mc/Summit/assets/110509017/c5273ca1-ae96-4da4-8954-c4e732b2c0b9)

- Device : Samsung S22 Ultra
 - OS: Android 
 - App Type: mobile app
 - Version: app version 2.4.4, google play store version 2.4.6

**Additional context**
Did happen in a prior version, and now it has reccured.

**Comment by pete-mc** [comment]
Thanks for the pick-up, I was making the new version in parallel and thought I had brought across all the fixes, must have missed this one. As you have noticed the mobile app version will now be different to the what the website shows which should allow updates to the web bit like this much faster.

**Comment by pete-mc** [comment]
Fixed this is 2.5.2, I will see what else I can squeeze in this update before it is released.
