### ISSUE TITLE
Feature Request: Sticky column for tables

### ISSUE THREAD

**Issue by AceLeader2023** [pete-mc/Summit#71]
**Is your feature request related to a problem? Please describe.**
Currently, when scrolling on the phone, you sight of the name in the tables and the badge type in the Badge Presentation Report. 

**Describe the solution you'd like**
I would suggest making at least the first column sticky when scrolling so that you don't lose sight of it. 

Additionally, for Milestone, OAS and Peak Award report also making the 1st row sticky would also help. 

----
This is just a suggestion to make the app a little more friendlier on smaller devices such as phones. 

And if you could somehow do this feature on the Terrain side of for OAS recording, that would be awesome too. 

Thank you for all your hard work. I really appreciate the features that are already available.

**Comment by pete-mc** [comment]
Yep good idea, you may have also noticed the new display settings option. The plan for that is to make ui changes to terrain possible, so let me know any others for the like the terrain oas screen as most of thosr things should be possible.

**Comment by pete-mc** [comment]
In v3 I have added these to the tables where it makes sense or is possible. 

There is a known bug with the table software I use that prevents sticky columns being used with the type of rendering I am doing for the OAS report. Hopefully when they sort out that issue I can turn in on for OAS as well.
