### ISSUE TITLE
Feature Request: Improve printability of OAS Summary

### ISSUE THREAD

**Issue by ScoutLeaderDid** [pete-mc/Summit#72]
Hi Pete,

Your OAS Summary report is brilliant. It gives a simple overview of progress and allows leaders to quickly focus on Scouts who need to start or progress further. I recently rescaled it, printed and placed it on our process board for the start of the year.

Two things I like to see improved.
1. I need the extract from Excel with darker fonts and black lines. It is hard to read when printed. See image attached.
2. Give an option of Excel or PDF. A PDF option is better as it saves time for the leaders. A PDF option will save the leaders in formatting and rescaling the information. I also ask  you add the word Summit to the title as well, ie Scouts | Terrain | Summit

Regards,
Did
![OAS Summary Report Summit 18012024](https://github.com/pete-mc/Summit/assets/155197725/adbbac34-10ae-487f-b7f5-785921aa4fbe)

**Comment by pete-mc** [comment]
I should be able to do those changes fairly easily, I will get these out in the next version.

**Comment by pete-mc** [comment]
Let me know how the new print outs work in version 3, I will close this for now but happy to take more feedback.
