### ISSUE TITLE
Feature Request: Tick on concluded events

### ISSUE THREAD

**Issue by AceLeader2023** [pete-mc/Summit#73]
**Is your feature request related to a problem? Please describe.**
Currently, when looking at events on the programming page on Scouts | Terrain, there is no way to know if the event has been concluded or not concluded. 

**Describe the solution you'd like**
Would it be possible to have a small green tick next to the event name?

**Describe alternatives you've considered**
An alternative is that we could have a report of all the events in x range on the Summit side that could have a link to each event that hasn't been concluded.

**Additional context**
I know that I will be using the bulk calendar feature on the Summit side, but it will be handy to know which events haven't been concluded.

**Comment by pete-mc** [comment]
Adding a tick should be pretty straight forward. I was also planning on making a nicer calendar page generally in the future so an icon for the status would make sense to add to that too. Will add this to my list for the next version.

**Comment by pete-mc** [comment]
This is fixed in the new calendar in the V3 version.
