### ISSUE TITLE
Bug: Bulk Calendar - Scout Method

### ISSUE THREAD

**Issue by AceLeader2023** [pete-mc/Summit#74]
**Describe the bug**
When creating a program entry on Terrain | Summit, it only allows you to select 1 Scout Method, whereas in Scouts | Terrain you can select multiple.

**To Reproduce**
1. Go to **Bulk Calendar**
2. Create a new entry and try and select 2 Scout Methods

**Expected behavior**
I expect to be able to select multiple Scout Methods

**Screenshots**
Terrain | Summit
<img width="952" alt="image" src="https://github.com/pete-mc/Summit/assets/110509017/0450aa71-71d5-4fae-87ad-5533efeaa873">

Scouts | Terrain
<img width="850" alt="image" src="https://github.com/pete-mc/Summit/assets/110509017/fef59474-498b-4320-a508-d9cd707d8540">

- Device : Lenovo Ideapad
 - OS: Windows
 - App Type: Chrome
 - Version: 2.4.0

**Additional context**
Additionally, this would also apply to organisers, lead and assist columns too.

**Comment by pete-mc** [comment]
I probably need to add instructions but just hold down CRTL and you can click more than one.

**Comment by pete-mc** [comment]
Let me know if it works and I can close the ticket.

**Comment by AceLeader2023** [comment]
All good. Instructions would be good in a future build for those who would not know.

Thank you for all your hard work building this awesome extension.
