### ISSUE TITLE
Bug: undefined error - bulk calendar

### ISSUE THREAD

**Issue by AceLeader2023** [pete-mc/Summit#77]
**Describe the bug**
I am not able to tell what the Error is in the bulk calendar feature.

**To Reproduce**
1. Go to bulk calendar
2. Type in below details

**Expected behavior**
It is expected to remove from list and send data into terrain calendar or tell me what the error is.
<img width="452" alt="image" src="https://github.com/pete-mc/Summit/assets/110509017/628139d3-800f-4ed1-92e5-2e6f692ba1e4">

Output behavior outcome:
<img width="588" alt="image" src="https://github.com/pete-mc/Summit/assets/110509017/1346b663-6ac1-4eb1-b398-947289305f13">

- Device : Lenovo Ideapad
 - OS: Windows
 - App Type: Chrome
 - Version: 2.5.1

Additionally, It didn't remove other events; I had to remove them manually to figure out which ones were not uploaded.

**Comment by pete-mc** [comment]
did you work out which one was causing the issue? If so, can you try to do that as a single submission? Finally, if it still errors can you open dev tools in chrome or edge (it is the same process) and see what error Terrain returned. 

To open DevTools, right-click the webpage, and then select Inspect. Or, press Ctrl+Shift+J (Windows, Linux) or Command+Option+J (macOS). DevTools opens.

In DevTools, on the Activity Bar, select the Network tab. If that tab isn't visible, click the More tools (More tools icon) button:

While it is open try to cause the error to occur and watch the [network messages](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/network/#log-network-activity)

The network request that caused the issue should be red if Terrain did not process it. Then [inspect the request](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/network/#inspect-the-details-of-the-resource) and look at the Response tab and let me know what it says.

**Comment by AceLeader2023** [comment]
For On Wheels/ Wide Games and Bushwalk event entry: 
<img width="319" alt="image" src="https://github.com/pete-mc/Summit/assets/110509017/fe50958f-9542-4fb9-88c6-92a9c468798d">

**Comment by pete-mc** [comment]
ah, I see what I did there, for outdoor activities the value needs to be outdoors, it is the only plural in the list. Must neve had selected that in my tests. I have fixed this and it will be in the 2.5.2 update when I get it out.

**Comment by AceLeader2023** [comment]
Thank you for being so proactive. 

I look forward to the release.
