### ISSUE TITLE
Bug: Duplication of OAS Stage Level in OAS Summary Report

### ISSUE THREAD

**Issue by ScoutLeaderDid** [pete-mc/Summit#80]
Hi,
When generating the OAS Summary report, I found a Scout with two different OAS stage levels listed.

**Expected behaviour**
My expectation is the highest OAS stage level that is awarded, should be listed only - not all of them.

**Screenshots**
![OAS Stage duplication 220124](https://github.com/pete-mc/Summit/assets/155197725/24cc1ec1-cfdb-4fdf-b43f-0589041c26f6)

- Device : Lenovo Desktop
 - OS: Windows
 - App Type: Chrome
 - Version: Latest

With thanks
Did

**Comment by pete-mc** [comment]
Thats weird, the only time that it should look like that is when they start to stream like bushcraft -> Pioneering, Survival and camping does not stream. I will have a look when I get home tonight.

**Comment by pete-mc** [comment]
I have sorted out this one in the version 3 I am currently working on, hopefully I should be able to get it out shortly.
