### ISSUE TITLE
Bug: OAS Disciplines are out of order in OAS Summary Report

### ISSUE THREAD

**Issue by CrispyCamper** [pete-mc/Summit#86]
**Describe the bug**
In the OAS Summary Report, the OAS Disciplines are out of order. Specifically, "Bushwalking" erroneously comes before "Bushcraft"

**To Reproduce**
1. Go to Summit
2. Click on OAS Summary Report
3. Wait for content to load
4. See they are out of order 

**Expected behavior**
They should be ordered alphabetically within their respective catergories which are themselves ordered Core, Terrafirma, Water. (Ie Bushcraft, Bushwalking, Camping, Alpine, Cycling, Vertical, Aquatics, Boating, Paddling.)
This is the order they are presented in every publication from Scouts Australia.

**Screenshots**
![Screenshot 2024-01-24 155953](https://github.com/pete-mc/Summit/assets/110330806/d92c52bf-e8be-49bb-b72f-a53cfc28d904)

- Device: HP Laptop 15s-fq4011TU
- OS: Windows 11 22H2
- Chrome Version: 120.0.6099.225
- App Type: Chrome Extension
- Version: V2.5.2

**Additional context**
Occurs on every device I tested it with

**Comment by pete-mc** [comment]
Thanks for picking up this one, I am currently rebuilding each of the reports as part of v3. I will match the orders with the published books.

**Comment by pete-mc** [comment]
This is fixed in the new V3 version.
