### ISSUE TITLE
Feature Request: [safe as draft for the bulk calendar entry

### ISSUE THREAD

**Issue by Peter280768** [pete-mc/Summit#88]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I would like to be able to use the bulk entry and save it as draft before I upload into the Terrain Calendar, as I would not always be entering all the weekly activites at teh same time

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.  currenlty I have not come up with any alternatives a=other than to add three or four enteries at once and them come back later to add more or the rest.

**Additional context**
Add any other context or screenshots about the feature request here.  I went to add some term dates and signed out while i confrmed with the scout leader on a joint night, and when I came back all my dates were gone.  Sadly no screen shots available.

**Comment by pete-mc** [comment]
Makes sense I am currently rebuilding this screen for version 3 so I will see if I can add some sort of draft feature.

**Comment by pete-mc** [comment]
In version 3 we now have a new calendar which saves as you go and allows you to quickly delete / fix any upcoming events. This should solve these sorts of issues for you. Version 3 should be about in the next few weeks.

**Comment by Peter280768** [comment]
That sounds awesome thankyou

**Comment by pete-mc** [comment]
This is fixed in the new V3 version.

**Comment by Peter280768** [comment]
Thank Peter
