### ISSUE TITLE
Bug: Bulk Calendar entry - Not accepting 'Outdoor' challenge area types

### ISSUE THREAD

**Issue by wilsteady** [pete-mc/Summit#92]
When using the bulk-program entry, getting an issue where it fails on calendar events which have 'Outdoors' set as their challenge area type. All others work fine without incident. Faulty entries worked as soon as the location was changed to something not Outdoors.
![image](https://github.com/pete-mc/Summit/assets/12633684/a2e7b916-5ce3-41c2-9275-14d5ce53b943)
![image](https://github.com/pete-mc/Summit/assets/12633684/fb0cf490-2651-42df-a2a2-6d786e864dde)

**Comment by pete-mc** [comment]
Can you check what version you are running? I thought the spelling issue I had that caused this was resolved but maybe it is a new issue.
